# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
Product.create(nameproduct:'Adaptador hembra 1/2 pvc',unitprice:'500.0',quantity:'')
Product.create(nameproduct:'Adaptador macho 1/2 pvc',unitprice:'500.0',quantity:'')
Product.create(nameproduct:'Codo 1/2 pvc',unitprice:'700.0',quantity:'')
Product.create(nameproduct:'Semicodo 1/2 pvc',unitprice:'900.0',quantity:'')
Product.create(nameproduct:'Tapón liso 1/2 pvc',unitprice:'500.0',quantity:'')
Product.create(nameproduct:'Tapón roscado 1/2 pvc',unitprice:'500.0',quantity:'')
Product.create(nameproduct:'Tee 1/2 pvc',unitprice:'800.0',quantity:'')
Product.create(nameproduct:'Tee reducida 1/2 x 3/4 pvc',unitprice:'1900.0',quantity:'')
Product.create(nameproduct:'Unión 1/2 pvc',unitprice:'500.0',quantity:'')
Product.create(nameproduct:'Universal 1/2 pvc',unitprice:'3500.0',quantity:'')
Product.create(nameproduct:'Unión Dresser 1/2 pvc',unitprice:'6000.0',quantity:'')
Product.create(nameproduct:'Unión Antideslizante 1/2 pvc',unitprice:'5500.0',quantity:'')
Product.create(nameproduct:'Tubo pvc 1/2 x 6 metros',unitprice:'20000.00',quantity:'')
Product.create(nameproduct:'Tubo pvc 1/2 x 1 metro',unitprice:'3500.00',quantity:'')
Product.create(nameproduct:'Tubo pvc 1/2 x 50 cm',unitprice:'1800.00',quantity:'')
Product.create(nameproduct:'Tubo pvc 1/2 x cm',unitprice:'50.00',quantity:'')
Product.create(nameproduct:'Adaptador hembra 3/4 pvc',unitprice:'800.0',quantity:'')
Product.create(nameproduct:'Adaptador macho 3/4 pvc',unitprice:'800.0',quantity:'')
Product.create(nameproduct:'Codo 3/4 pvc',unitprice:'900.0',quantity:'')
Product.create(nameproduct:'Semicodo 3/4 pvc',unitprice:'1400.0',quantity:'')
Product.create(nameproduct:'Tapón liso 3/4 pvc',unitprice:'800.0',quantity:'')
Product.create(nameproduct:'Tapón roscado 3/4 pvc',unitprice:'1300.0',quantity:'')
Product.create(nameproduct:'Tee 3/4 pvc',unitprice:'1300.00',quantity:'')
Product.create(nameproduct:'Unión 3/4 pvc',unitprice:'700.0',quantity:'')
Product.create(nameproduct:'Universal 3/4 pvc',unitprice:'5000.0',quantity:'')
Product.create(nameproduct:'Unión Dresser 3/4 pvc',unitprice:'8500.0',quantity:'')
Product.create(nameproduct:'Unión Antideslizante 3/4 pvc',unitprice:'6500.0',quantity:'')
Product.create(nameproduct:'Tubo pvc 3/4 x 6 metros',unitprice:'28500.00',quantity:'')
Product.create(nameproduct:'Tubo pvc 3/4 x 1 metro',unitprice:'4400.0',quantity:'')
Product.create(nameproduct:'Tubo pvc 3/4 x 50 cm',unitprice:'2200.0',quantity:'')
Product.create(nameproduct:'Tubo pvc 3/4 x cm',unitprice:'100.00',quantity:'')
Product.create(nameproduct:'Adaptador hembra 1 pvc',unitprice:'1600.0',quantity:'')
Product.create(nameproduct:'Adaptador macho 1 pvc',unitprice:'1600.0',quantity:'')
Product.create(nameproduct:'Codo 1 pvc',unitprice:'2000.00',quantity:'')
Product.create(nameproduct:'Semicodo 1 pvc',unitprice:'2400.0',quantity:'')
Product.create(nameproduct:'Tapón liso 1 pvc',unitprice:'1200.0',quantity:'')
Product.create(nameproduct:'Tapón roscado 1 pvc',unitprice:'1800.0',quantity:'')
Product.create(nameproduct:'Tee 1 pvc',unitprice:'2900.00',quantity:'')
Product.create(nameproduct:'Tee 1 x 1/2 pvc',unitprice:'3500.0',quantity:'')
Product.create(nameproduct:'Tee 1 x 3/4 pvc',unitprice:'3500.0',quantity:'')
Product.create(nameproduct:'Unión 1 pvc',unitprice:'1000.0',quantity:'')
Product.create(nameproduct:'Universal 1 pvc',unitprice:'9000.0',quantity:'')
Product.create(nameproduct:'Unión Dresser 1 pvc',unitprice:'9800.0',quantity:'')
Product.create(nameproduct:'Unión Antideslizante 1 pvc',unitprice:'8500.0',quantity:'')
Product.create(nameproduct:'Tubo pvc 1 x 6 metros',unitprice:'35200.0',quantity:'')
Product.create(nameproduct:'Tubo pvc 1 x 1 metro',unitprice:'6400.00',quantity:'')
Product.create(nameproduct:'Tubo pvc 1 x 50 cm',unitprice:'3000.0',quantity:'')
Product.create(nameproduct:'Tubo pvc 1 x cm',unitprice:'100.00',quantity:'')
Product.create(nameproduct:'Adaptador hembra 1-1/4 pvc',unitprice:'3000.0',quantity:'')
Product.create(nameproduct:'Adaptador macho 1-1/4 pvc',unitprice:'3000.0',quantity:'')
Product.create(nameproduct:'Codo 1-1/4 pvc',unitprice:'3400.0',quantity:'')
Product.create(nameproduct:'Semicodo 1-1/4 pvc',unitprice:'4700.0',quantity:'')
Product.create(nameproduct:'Tapón liso 1-1/4 pvc',unitprice:'2600.0',quantity:'')
Product.create(nameproduct:'Tapón roscado 1-1/4 pvc',unitprice:'3000.0',quantity:'')
Product.create(nameproduct:'Tee 1-1/4 pvc',unitprice:'5800.0',quantity:'')
Product.create(nameproduct:'Unión 1-1/4 pvc',unitprice:'1800.0',quantity:'')
Product.create(nameproduct:'Universal 1-1/4 pvc',unitprice:'14000.0',quantity:'')
Product.create(nameproduct:'Tubo pvc 1-1/4 x 6 metros',unitprice:'43000.0',quantity:'')
Product.create(nameproduct:'Tubo pvc 1-1/4 x 1 metro',unitprice:'7200.0',quantity:'')
Product.create(nameproduct:'Tubo pvc 1-1/4 x 50 cm',unitprice:'3600.0',quantity:'')
Product.create(nameproduct:'Tubo pvc 1-1/4 x cm',unitprice:'150.00',quantity:'')
Product.create(nameproduct:'Adaptador hembra 1-1/2 pvc',unitprice:'4800.0',quantity:'')
Product.create(nameproduct:'Adaptador macho 1-1/2 pvc',unitprice:'4000.0',quantity:'')
Product.create(nameproduct:'Codo 1-1/2 pvc',unitprice:'6000.0',quantity:'')
Product.create(nameproduct:'Semicodo 1-1/2 pvc',unitprice:'7000.0',quantity:'')
Product.create(nameproduct:'Tapón liso 1-1/2 pvc',unitprice:'3200.0',quantity:'')
Product.create(nameproduct:'Tapón roscado 1-1/2 pvc',unitprice:'4000.0',quantity:'')
Product.create(nameproduct:'Tee 1-1/2 pvc',unitprice:'8000.00',quantity:'')
Product.create(nameproduct:'Unión 1-1/2 pvc',unitprice:'2800.0',quantity:'')
Product.create(nameproduct:'Universal 1-1/2 pvc',unitprice:'30700.00',quantity:'')
Product.create(nameproduct:'Tubo pvc 1-1/2 x 6 metros',unitprice:'57200.0',quantity:'')
Product.create(nameproduct:'Tubo pvc 1-1/2 x 1 metro',unitprice:'9500.0',quantity:'')
Product.create(nameproduct:'Tubo pvc 1-1/2 x 50 cm',unitprice:'5200.00',quantity:'')
Product.create(nameproduct:'Tubo pvc 1-1/2 x cm',unitprice:'200.00',quantity:'')
Product.create(nameproduct:'Adaptador hembra 2 pvc',unitprice:'7800.0',quantity:'')
Product.create(nameproduct:'Adaptador macho 2 pvc',unitprice:'5300.0',quantity:'')
Product.create(nameproduct:'Codo 2 pvc',unitprice:'9000.0',quantity:'')
Product.create(nameproduct:'Semicodo 2 pvc',unitprice:'10800.0',quantity:'')
Product.create(nameproduct:'Tapón liso 2 pvc',unitprice:'5000.0',quantity:'')
Product.create(nameproduct:'Tapón roscado 2 pvc',unitprice:'6800.0',quantity:'')
Product.create(nameproduct:'Tee 2 pvc',unitprice:'12500.0',quantity:'')
Product.create(nameproduct:'Unión 2 pvc',unitprice:'4500.0',quantity:'')
Product.create(nameproduct:'Universal 2 pvc',unitprice:'30500.0',quantity:'')
Product.create(nameproduct:'Tubo pvc 2 x 6 metros',unitprice:'85000.0',quantity:'')
Product.create(nameproduct:'Tubo pvc 2 x 1 metro',unitprice:'14200.0',quantity:'')
Product.create(nameproduct:'Tubo pvc 2 x 50 cm',unitprice:'7100.0',quantity:'')
Product.create(nameproduct:'Tubo pvc 2 x cm',unitprice:'300.00',quantity:'')
Product.create(nameproduct:'Adaptador hembra 2-1/2 pvc',unitprice:'14000.0',quantity:'')
Product.create(nameproduct:'Adaptador macho 2-1/2 pvc',unitprice:'12800.0',quantity:'')
Product.create(nameproduct:'Codo 2-1/2 pvc',unitprice:'24800.0',quantity:'')
Product.create(nameproduct:'Semicodo 2-1/2 pvc',unitprice:'25600.0',quantity:'')
Product.create(nameproduct:'Tapón liso 2-1/2 pvc',unitprice:'11300.0',quantity:'')
Product.create(nameproduct:'Tapón roscado 2-1/2 pvc',unitprice:'14000.0',quantity:'')
Product.create(nameproduct:'Tee 2-1/2 pvc',unitprice:'26800.0',quantity:'')
Product.create(nameproduct:'Unión 2-1/2 pvc',unitprice:'12800.0',quantity:'')
Product.create(nameproduct:'Universal 2-1/2 pvc',unitprice:'30800.0',quantity:'')
Product.create(nameproduct:'Tubo pvc 2-1/2 x 6 metros',unitprice:'108000.0',quantity:'')
Product.create(nameproduct:'Tubo pvc 2-1/2 x 1 metro',unitprice:'18000.0',quantity:'')
Product.create(nameproduct:'Tubo pvc 2-1/2 x 50 cm',unitprice:'9000.0',quantity:'')
Product.create(nameproduct:'Tubo pvc 2-1/2 x cm',unitprice:'500.0',quantity:'')
Product.create(nameproduct:'Adaptador hembra 3 pvc',unitprice:'21800.0',quantity:'')
Product.create(nameproduct:'Adaptador macho 3 pvc',unitprice:'17800.0',quantity:'')
Product.create(nameproduct:'Codo 3 pvc',unitprice:'32500.0',quantity:'')
Product.create(nameproduct:'Semicodo 3 pvc',unitprice:'32500.0',quantity:'')
Product.create(nameproduct:'Tapón liso 3 pvc',unitprice:'17400.0',quantity:'')
Product.create(nameproduct:'Tapón roscado 3 pvc',unitprice:'21800.0',quantity:'')
Product.create(nameproduct:'Tee 3 pvc',unitprice:'43000.0',quantity:'')
Product.create(nameproduct:'Unión 3 pvc',unitprice:'18000.0',quantity:'')
Product.create(nameproduct:'Universal 3 pvc',unitprice:'49500.0',quantity:'')
Product.create(nameproduct:'Tubo pvc 3 x 6 metros',unitprice:'',quantity:'')
Product.create(nameproduct:'Tubo pvc 3 x 1 metro',unitprice:'',quantity:'')
Product.create(nameproduct:'Buje 3/4 x 1/2 pvc',unitprice:'600.0',quantity:'')
Product.create(nameproduct:'Tubo pvc 3 x 50 cm',unitprice:'',quantity:'')
Product.create(nameproduct:'Adaptador hembra 4 pvc',unitprice:'',quantity:'')
Product.create(nameproduct:'Adaptador macho 4 pvc',unitprice:'',quantity:'')
Product.create(nameproduct:'Codo 4 pvc',unitprice:'',quantity:'')
Product.create(nameproduct:'Semicodo 4 pvc',unitprice:'',quantity:'')
Product.create(nameproduct:'Tapón liso 4 pvc',unitprice:'',quantity:'')
Product.create(nameproduct:'Tapón roscado 4 pvc',unitprice:'',quantity:'')
Product.create(nameproduct:'Tee 4 pvc',unitprice:'',quantity:'')
Product.create(nameproduct:'Unión 4 pvc',unitprice:'',quantity:'')
Product.create(nameproduct:'Universal 4 pvc',unitprice:'',quantity:'')
Product.create(nameproduct:'Buje 1 x 1/2 pvc',unitprice:'1200.0',quantity:'')
Product.create(nameproduct:'Buje 1 x 3/4 pvc',unitprice:'1200.0',quantity:'')
Product.create(nameproduct:'Buje 1-1/4 x 1/2 pvc',unitprice:'1800.0',quantity:'')
Product.create(nameproduct:'Buje 1-1/4 x 3/4 pvc',unitprice:'1800.0',quantity:'')
Product.create(nameproduct:'Buje 1-1/4 x 1 pvc',unitprice:'1800.0',quantity:'')
Product.create(nameproduct:'Buje 1-1/2 x 1/2 pvc',unitprice:'3400.0',quantity:'')
Product.create(nameproduct:'Buje 1-1/2 x 3/4 pvc',unitprice:'3400.0',quantity:'')
Product.create(nameproduct:'Buje 1-1/2 x 1 pvc',unitprice:'3400.0',quantity:'')
Product.create(nameproduct:'Buje 1-1/2 x 1-1/4 pvc',unitprice:'3400.0',quantity:'')
Product.create(nameproduct:'Buje 2 x 1/2 pvc',unitprice:'5000.0',quantity:'')
Product.create(nameproduct:'Buje 2 x 3/4 pvc',unitprice:'5000.0',quantity:'')
Product.create(nameproduct:'Buje 2 x 1 pvc',unitprice:'5000.0',quantity:'')
Product.create(nameproduct:'Buje 2 x 1-1/4 pvc',unitprice:'5000.0',quantity:'')
Product.create(nameproduct:'Buje 2 x 1-1/2 pvc',unitprice:'4700.0',quantity:'')
Product.create(nameproduct:'Buje 2-1/2 x 1-1/2 pvc',unitprice:'10800.0',quantity:'')
Product.create(nameproduct:'Buje 2-1/2 x 2 pvc',unitprice:'10800.0',quantity:'')
Product.create(nameproduct:'Buje 3 x 2 pvc',unitprice:'16500.0',quantity:'')
Product.create(nameproduct:'Buje 3 x 2-1/2 pvc',unitprice:'16500.0',quantity:'')
Product.create(nameproduct:'Buje 4 x 2 pvc',unitprice:'26000.0',quantity:'')
Product.create(nameproduct:'Buje 4 x 2-1/2 pvc',unitprice:'26000.0',quantity:'')
Product.create(nameproduct:'Buje 4 x 3 pvc',unitprice:'26000.0',quantity:'')
Product.create(nameproduct:'Adaptador hembra 1/2 cpvc',unitprice:'2300.0',quantity:'')
Product.create(nameproduct:'Buje 3/4 x 1/2 cpvc',unitprice:'1600.0',quantity:'')
Product.create(nameproduct:'Adaptador macho 1/2 cpvc',unitprice:'1600.00',quantity:'')
Product.create(nameproduct:'Codo 1/2 cpvc',unitprice:'1600.0',quantity:'')
Product.create(nameproduct:'Semicodo 1/2 cpvc',unitprice:'1600.0',quantity:'')
Product.create(nameproduct:'Tapón 1/2 cpvc',unitprice:'1400.00',quantity:'')
Product.create(nameproduct:'Tee 1/2 cpvc',unitprice:'1800.0',quantity:'')
Product.create(nameproduct:'Union 1/2 cpvc',unitprice:'1300.0',quantity:'')
Product.create(nameproduct:'Universal 1/2 cpvc',unitprice:'8700.0',quantity:'')
Product.create(nameproduct:'Unión Dresser 1/2 cpvc',unitprice:'',quantity:'')
Product.create(nameproduct:'Tubo pvc 1/2 cpvc x 6 metros',unitprice:'17800.0',quantity:'')
Product.create(nameproduct:'Tubo pvc 1/2 cpvc x 1 metro',unitprice:'6000.0',quantity:'')
Product.create(nameproduct:'Tubo pvc 1/2 cpvc x 50 cm',unitprice:'3000.0',quantity:'')
Product.create(nameproduct:'Tubo pvc 1/2 cpvc x cm',unitprice:'150.00',quantity:'')
Product.create(nameproduct:'Adaptador hembra 3/4 cpvc',unitprice:'3000.0',quantity:'')
Product.create(nameproduct:'Buje 3/4 x 1 cpvc',unitprice:'5000.0',quantity:'')
Product.create(nameproduct:'Adaptador macho 3/4 cpvc',unitprice:'1800.0',quantity:'')
Product.create(nameproduct:'Codo 3/4 cpvc',unitprice:'2400.0',quantity:'')
Product.create(nameproduct:'Semicodo 3/4 cpvc',unitprice:'2400.0',quantity:'')
Product.create(nameproduct:'Tapón 3/4 cpvc',unitprice:'1500.0',quantity:'')
Product.create(nameproduct:'Tee 3/4 cpvc',unitprice:'2800.0',quantity:'')
Product.create(nameproduct:'Union 3/4 cpvc',unitprice:'1500.0',quantity:'')
Product.create(nameproduct:'Universal 3/4 cpvc',unitprice:'9800.0',quantity:'')
Product.create(nameproduct:'Unión Dresser 3/4 cpvc',unitprice:'',quantity:'')
Product.create(nameproduct:'Tubo pvc 3/4 cpvc x 6 metros',unitprice:'29500.0',quantity:'')
Product.create(nameproduct:'Tubo pvc 3/4 cpvc x 1 metro',unitprice:'9800.0',quantity:'')
Product.create(nameproduct:'Tubo pvc 3/4 cpvc x 50 cm',unitprice:'4900.0',quantity:'')
Product.create(nameproduct:'Tubo pvc 3/4 cpvc x cm',unitprice:'200.00',quantity:'')
Product.create(nameproduct:'Codo CxC 1-1/2 Sanitario',unitprice:'3500.0',quantity:'')
Product.create(nameproduct:'Codo CxE 1-1/2 Sanitario',unitprice:'3800.0',quantity:'')
Product.create(nameproduct:'Semicodo CxC 1-1/2 Sanitario',unitprice:'3800.0',quantity:'')
Product.create(nameproduct:'Semicodo CxE 1-1/2 Sanitario',unitprice:'3800.0',quantity:'')
Product.create(nameproduct:'Sifón completo 1-1/2 Sanitario (2 Codos CxE y 1 Codo CxC)',unitprice:'11100.0',quantity:'')
Product.create(nameproduct:'Sifón con tapón 1-1/2 Sanitario',unitprice:'6800.0',quantity:'')
Product.create(nameproduct:'Tapón prueba 1-1/2 Sanitario',unitprice:'2500.0',quantity:'')
Product.create(nameproduct:'Tee 1-1/2 Sanitario',unitprice:'6000.0',quantity:'')
Product.create(nameproduct:'Tee doble 1-1/2 Sanitario',unitprice:'10000.0',quantity:'')
Product.create(nameproduct:'Unión 1-1/2 Sanitario',unitprice:'2500.0',quantity:'')
Product.create(nameproduct:'Tubo pvc 1-1/2 Sanitario x 6 metros',unitprice:'49800.00',quantity:'')
Product.create(nameproduct:'Tubo pvc 1-1/2 Sanitario x 1 metro',unitprice:'8500.00',quantity:'')
Product.create(nameproduct:'Tubo pvc 1-1/2 Sanitario x 50 cm',unitprice:'4300.00',quantity:'')
Product.create(nameproduct:'Tubo pvc 1-1/2 Sanitario x cm',unitprice:'150.00',quantity:'')
Product.create(nameproduct:'Tubo pvc 1-1/2 Ventilación x 6 metros',unitprice:'29000.0',quantity:'')
Product.create(nameproduct:'Tubo pvc 1-1/2 Ventilación x 1 metro',unitprice:'4900.0',quantity:'')
Product.create(nameproduct:'Tubo pvc 1-1/2 Ventilación x 50 cm',unitprice:'2500.0',quantity:'')
Product.create(nameproduct:'Tubo pvc 1-1/2 Ventilación x cm',unitprice:'100.0',quantity:'')
Product.create(nameproduct:'Adaptador de limpieza 2 Sanitario',unitprice:'7800.0',quantity:'')
Product.create(nameproduct:'Buje soldado 2 x 1-1/2 Sanitario',unitprice:'3800.0',quantity:'')
Product.create(nameproduct:'Codo CxC 2 Sanitario',unitprice:'3500.00',quantity:'')
Product.create(nameproduct:'Codo CxE 2 Sanitario',unitprice:'3600.0',quantity:'')
Product.create(nameproduct:'Semicodo CxC 2 Sanitario',unitprice:'4800.0',quantity:'')
Product.create(nameproduct:'Semicodo CxE 2 Sanitario',unitprice:'4800.0',quantity:'')
Product.create(nameproduct:'Sifón con tapón 2 Sanitario',unitprice:'8800.0',quantity:'')
Product.create(nameproduct:'Sifón 180 sin codo 2 Sanitario',unitprice:'6900.0',quantity:'')
Product.create(nameproduct:'Sifón 180º completo (más Codo CxE) 2 Sanitario',unitprice:'10500.0',quantity:'')
Product.create(nameproduct:'Tapón prueba 2 Sanitario',unitprice:'2500.0',quantity:'')
Product.create(nameproduct:'Tee 2 Sanitario',unitprice:'5500.0',quantity:'')
Product.create(nameproduct:'Tee reducida 2 x 1-1/2  Sanitario',unitprice:'6700.0',quantity:'')
Product.create(nameproduct:'Tee doble red',unitprice:'11000.0',quantity:'')
Product.create(nameproduct:'Tee doble reducida 2 x 1-1/2 2 Sanitario',unitprice:'9800.0',quantity:'')
Product.create(nameproduct:'Unión  2 Sanitario',unitprice:'3500.0',quantity:'')
Product.create(nameproduct:'Yee  2 Sanitario',unitprice:'7800.0',quantity:'')
Product.create(nameproduct:'Yee doble red  2 Sanitario',unitprice:'11500.0',quantity:'')
Product.create(nameproduct:'Yee reducida 3 x 2 Sanitario',unitprice:'13800.0',quantity:'')
Product.create(nameproduct:'Yee doble reducida 2 x 3 x 2 Sanitario',unitprice:'21500.0',quantity:'')
Product.create(nameproduct:'Yee doble reducida 2 x 4 x 2 Sanitario',unitprice:'25000.0',quantity:'')
Product.create(nameproduct:'Tubo pvc 2 Sanitario x 6 metros',unitprice:'58000.0',quantity:'')
Product.create(nameproduct:'Tubo pvc 2 Sanitario x 1 metro',unitprice:'9800.0',quantity:'')
Product.create(nameproduct:'Tubo pvc 2 Sanitario x 50 cm',unitprice:'4900.0',quantity:'')
Product.create(nameproduct:'Tubo pvc 2 Sanitario x cm',unitprice:'300.0',quantity:'')
Product.create(nameproduct:'Tubo pvc 2 Ventilación x 6 metros',unitprice:'39000.0',quantity:'')
Product.create(nameproduct:'Tubo pvc 2 Ventilación x 1 metro',unitprice:'6500.0',quantity:'')